# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  solutionFile: 'src/softaware.Cqs.sln'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1'
  inputs:
    version: 3.1.x

- script: dotnet build $(solutionFile) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test $(solutionFile) --configuration $(buildConfiguration) --logger trx
  displayName: 'dotnet test $(buildConfiguration)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'

- task: CopyFiles@2
  inputs:
    TargetFolder: $(Build.ArtifactStagingDirectory)
    Contents: '**/*.nupkg'
    flattenFolders: true

- task: PublishBuildArtifacts@1